;;; init-modal.el --- Meow modal editing -*- lexical-binding: t -*-

(eval-when-compile (require 'use-package))

(require 'init-editor)
(require 'init-languages)
(require 'init-projects)
(require 'init-lsp)

(defun my-delete-other-windows-and-kill-minibuffer ()
  "Supprime les fenêtres additionnelles et ferme le minibuffer actif."
  (interactive)
  (when (active-minibuffer-window)
    (abort-recursive-edit))
  (delete-other-windows))

(defun my/meow-newline-and-insert ()
  (interactive)
  (newline)
  (unless (meow-insert-mode-p)
    (meow-insert)))

(defun my/meow-backspace-and-insert ()
  (interactive)
  (delete-backward-char 1)
  (unless (meow-insert-mode-p)
    (meow-insert)))

(defun my/meow-jump-back ()
  "Jump backward using better-jumper."
  (interactive)
  (better-jumper-jump-backward))

(defun my/meow-jump-forward ()
  "Jump forward using better-jumper."
  (interactive)
  (better-jumper-jump-forward))

(use-package meow
  :config
  (defun meow-setup ()
    (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
    (meow-leader-define-key
     '("?" . meow-cheatsheet)
     '("f" . find-file)
     '("p p" . my/project-switch-to-find-file)
     '("p f" . project-find-file)
     '("p b" . consult-project-buffer)
     '("b" . switch-to-buffer)
     '("d" . consult-flymake)
     '("D" . my/consult-flymake-project)
     '("s" . consult-eglot-symbols)
     '("k" . kill-buffer)
     '("w" . save-buffer)
     '("." . magit-status)
     '("t" . neotree-toggle)
     '("/" . consult-ripgrep)
     '("a" . eglot-code-actions)
     '("r" . eglot-rename)
     '("l f" . eglot-format)
     '("l d" . xref-find-definitions)
     '("," . xref-find-references)
     '("' c" . (lambda () (interactive) (compile "cargo build")))
     '("' t" . my/rust-run-test-at-point)
     '("' T" . (lambda () (interactive) (compile "cargo test")))
     '("' R" . (lambda () (interactive) (compile "cargo run"))))
    (meow-normal-define-key
     '("e" . er/expand-region)
     '("E" . er/contract-region)
     '("vv" . my/flip-selection-cursor)
     '("vs" . my/ts-select-statement)
     '("ve" . my/ts-select-expression-chain)
     '("vF" . my/ts-select-function-with-attrs)
     '("vf" . my/ts-select-function)
     '("vi" . my/ts-select-impl)
     '("vS" . my/ts-select-struct-expr)
     '("vt" . my/ts-select-trait)
     '("vb" . my/ts-select-block)
     '("h" . eldoc)
     '("H" . eldoc-doc-buffer)
     '("C" . mc/mark-next-like-this)
     '("j" . meow-join)
     '("d" . meow-kill)
     '("y" . meow-save)
     '("Y" . meow-clipboard-save)
     '("P" . meow-clipboard-yank)
     '("p" . meow-yank)
     '("/" . meow-visit)
     '("i" . meow-insert)
     '("x" . meow-line)
     '("Q" . my-delete-other-windows-and-kill-minibuffer)
     '("q" . kill-current-buffer)
     '("u" . undo)
     '("U" . undo-redo)
     '("n" . meow-search)
     '("g l" . end-of-line)
     '("g h" . beginning-of-line)
     '("'" . meow-mark-word)
     '(";" . comment-line)
     '("M-<up>" . backward-up-list)
     '("M-S-<up>" . meow-block)
     '("M-S-<left>" . my/meow-jump-back)
     '("M-S-<right>" . my/meow-jump-forward)
     '("M-RET" . xref-find-definitions)
     '("<backspace>" . my/meow-backspace-and-insert)
     '("RET" . my/meow-newline-and-insert)
     '("<escape>" . meow-cancel)))
  (meow-setup)
  (meow-global-mode 1)
  (dolist (key '("C-c" "C-g"))
    (define-key meow-insert-state-keymap (kbd key) #'meow-normal-mode))
  (define-key meow-insert-state-keymap [delete] #'delete-forward-char)
  (add-hook 'after-save-hook
            (lambda ()
              (when (meow-insert-mode-p)
                (meow-normal-mode)))))

(with-eval-after-load 'dired
  (define-key dired-mode-map (kbd "q") #'kill-current-buffer)
  (define-key dired-mode-map (kbd "Q") #'my-delete-other-windows-and-kill-minibuffer))

(with-eval-after-load 'magit
  (define-key magit-mode-map (kbd "q") #'kill-current-buffer)
  (define-key magit-mode-map (kbd "Q") #'my-delete-other-windows-and-kill-minibuffer)
  (define-key magit-mode-map [escape] (lookup-key global-map (kbd "M-g")))
  (define-key magit-mode-map (kbd "M-S-<left>") #'my/meow-jump-back)
  (define-key magit-mode-map (kbd "M-S-<right>") #'my/meow-jump-forward))

(provide 'init-modal)
;;; init-modal.el ends here
